### ISSUE TITLE
2.7.0 release bug

### ISSUE THREAD

**Issue by PydPiper** [json-editor/json-editor#1153]
### General information

- json-editor version: 2.7.0

### Steps to reproduce the behavior

- load any schema that has a dropdown with name `root.PROJECT` and defined it as `Eproject` then try to overwrite the value with `getEditor`

```javascript
          Eproject = new JSONEditor(document.getElementById('Eproject'),{schema: data});
          Eproject.getEditor('root.PROJECT').setValue(getCookie("PROJECT")) 
```

generates the following error on load in 2.7.0, this does not occur on 2.6.1

`Uncaught TypeError: Eproject.getEditor(...) is undefined`

**Comment by lionscribe** [comment]
Same issue here:
Following is Chrome stacktrace
    

> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getValue')
>     at t.lineOneColorCallback (create:914:59)
>     at t.value (jsoneditor.min.js:20:451780)
>     at o.value (jsoneditor.min.js:20:104422)
>     at o.value (jsoneditor.min.js:20:104616)
>     at o.value (jsoneditor.min.js:20:119659)
>     at o.value (jsoneditor.min.js:20:341131)
>     at jsoneditor.min.js:20:274740
>     at Array.forEach (<anonymous>)
>     at o.value (jsoneditor.min.js:20:274593)
>     at o.value (jsoneditor.min.js:20:108058)`

**Comment by germanbisurgi** [comment]
I am trying to reproduce the error but all seems to work like it should. Can you provide a complete example that i can use to reproduce this? With complete i mean, the simplest schema that trigger the error and, the javascript used to init the editor and if set the initial data too. Thanks and sorry for the inconvenience

**Comment by schmunk42** [comment]
@lionscribe There's no attachment.

**Comment by lionscribe** [comment]
[testeditor.zip](https://github.com/json-editor/json-editor/files/8565342/testeditor.zip)
Here you go.

**Comment by lionscribe** [comment]
Well that solved it. Must be that 2.6.1 was a little quicker, and won the race, so it worked. You may want to put in a warning to the console, if possible.
Thank you
