### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by navytux** [json-editor/json-editor#1384]
Hello once again,

I hit another problem where json-editor crashes in `expandSchema` with:

```
schemaloader.js:176 reference:'instance-erp5-input-schema.json#/definitions/tcpv4port' not found!
schemaloader.js:219 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'type')
    at eval (schemaloader.js:219:1)
    at Array.forEach (<anonymous>)
    at SchemaLoader.expandSchema (schemaloader.js:218:1)
    at SchemaLoader.expandRefs (schemaloader.js:186:1)
    at eval (schemaloader.js:90:1)
    at Array.forEach (<anonymous>)
    at SchemaLoader.allOf (schemaloader.js:89:1)
    at eval (schemaloader.js:228:1)
    at Array.forEach (<anonymous>)
    at SchemaLoader.expandSchema (schemaloader.js:226:1)
```

Similarly to #1383 the problem happens in `$ref`'ed schema with minimal reproducer provided below:

---- 8< ---- (top `schema.json`)
```json
{
  "$ref": "https://lab.nexedi.com/kirr/misc/raw/07ad4b6/lte/je-bug2.json"
}
```

---- 8< ---- (`je-bug2.json`)
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Parameters to instantiate ERP5",
  "type": "object",
  "definitions": {
    "tcpv4port": {
      "minimum": 0,
      "maximum": 65535,
      "type": "integer"
    }
  },
  "properties": {
    "zope-partition-dict": {
      "description": "Zope layout definition",
      "default": {
        "1": {}
      },
      "patternProperties": {
        ".*": {
          "properties": {
            "port-base": {
              "allOf": [
                {
                  "$ref": "#/definitions/tcpv4port"
                }
              ]
            }
          },
          "type": "object"
        }
      },
      "type": "object"
    }
  }
}
```

Thanks beforehand,
Kirill

### General information

- json-editor version: `2.10.1-38-g06f0117`

### Expected behavior

Schema loads ok, no crash.

### Actual behavior

Schema loader crashes.

### Steps to reproduce the behavior

[Direct link to bug example](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgAJFKpFCyqFAiIUAelMC8AOnhUAHlQAmMK1jqmA1jClTTdGEqmUpSmAAwA7GSOACx4AGwWUFSmXAC0eCIA5gBMVhy08CAAvmyIymAUvFQ+0sgoIDDwScE8cIVsUKoMhHhgYFCIUMEQ0Qo6AI4i3k68eIK8jrpkItjiKERyiFRszogQAvMTUzqOvDiCqBvYW6XllZB8jZeb2yCSvFHOsAhyvBBSkGqsBoz2urzIHDIdlQQxEr12ZDw2CoVS+vHyCFBNxACKRKKw2AExioWPhAURyL+AIgQJgIPWLx25LxHx8Qg+jkcpKZiApKLIbMOVGkiyk3JxzMpAuC80WyKS4qo8D5rJlvCwEAuDLBbGl7KwTQB114UEg4txUsFCyo8v5hN4AIodSu2It/KtcqoSX4ZEGDoqpKKRSAA==) .

**Comment by schmunk42** [comment]
Can you tell which section of the loaded schema is causing the error?

**Comment by navytux** [comment]
@schmunk42, thanks for feedback.

I'm not sure, but it seems to be related to interaction of `definitions/tcpv4port` and `zope-partition-dict/.*/port-base/allOf` and `zope-partition-dict/default`:

- if I remove "allOf" and make "port-base" to be just
  ```
            "port-base": {
              "$ref": "#/definitions/tcpv4port"
            }
  ```
  the crash goes away;
- if I replace "$ref" inside "allOf" with its content by myself:
  ```
            "port-base": {
              "allOf": [
                { 
                  "type": "integer"
                }
              ]
  ```
  the crash also goes away;
- if I remove "1" from "zope-partition-dict/default":
  ```
      "default": {
      },
  ```
  the crash also goes away.

As I'm newbie to javascript and json schemas what I originally posted seems to be already realatively minimal example. Maybe there is a way to make it more minimal, but I could not quickly find it.

For the reference this bug happens for real on the following schema, when it is `$ref`'ed: https://lab.nexedi.com/nexedi/slapos/raw/master/software/erp5/instance-erp5-input-schema.json

Kirill

**Comment by navytux** [comment]
This should be fixed by https://github.com/json-editor/json-editor/pull/1385 hopefully.
