### ISSUE TITLE
An error occurs when a dependency is defined after the field that depends on it

### ISSUE THREAD

**Issue by DCkQ6** [json-editor/json-editor#1536]
### General information

- json-editor version: master

A dependent field fails because its dependency is defined later in the shema.

### Expected behavior

The schema should be rendered without errors.

### Actual behavior

stack trace in console
```
editor.js:200 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at NumberEditor.checkDependency (editor.js:200:1)
    at eval (editor.js:148:1)
    at Array.forEach (<anonymous>)
    at NumberEditor.evaluateDependencies (editor.js:135:1)
    at Array.eval (editor.js:115:1)
    at JSONEditor.notifyWatchers (core.js:349:1)
    at CheckboxEditor.notify (editor.js:42:1)
    at CheckboxEditor.onChange (editor.js:51:1)
    at CheckboxEditor.register (editor.js:62:1)
    at CheckboxEditor.register (checkbox.js:18:1)
```

### Steps to reproduce the behavior

```javascript
{
    'title': 'Dependency chain support',
    'type': 'object',
    'properties': {
      'dependent_field_two': {
        'type': 'number',
        'options': {
          'dependencies': {
            'dependent_field_one': true
          }
        }
      },
      'dependent_field_one': {
        'type': 'boolean',
        'format': 'checkbox',
        'options': {
          'dependencies': {
            'dependency_chain_head': true
          }
        }
      },
      'dependency_chain_head': {
        'type': 'boolean',
        'default': false,
        'format': 'checkbox'
      }
    }
  }
```

**Comment by germanbisurgi** [comment]
fixed in #1548
