### ISSUE TITLE
exception on array of object with dependencies

### ISSUE THREAD

**Issue by rozo1** [json-editor/json-editor#361]
### General information

- json-editor version: 1.3.5 (latest)

### Actual behavior

TypeError: Cannot read property 'getEditor' of null
    at Class.checkDependency (f:\dev\vue\json-editor-test\node_modules\@json-editor\json-editor\dist\jsoneditor.js:1588:1)
    at Array.<anonymous> (f:\dev\vue\json-editor-test\node_modules\@json-editor\json-editor\dist\jsoneditor.js:1577:1)
    at JSONEditor.notifyWatchers (f:\dev\vue\json-editor-test\node_modules\@json-editor\json-editor\dist\jsoneditor.js:541:1)
    at Class.notify (f:\dev\vue\json-editor-test\node_modules\@json-editor\json-editor\dist\jsoneditor.js:1515:1)
    at Class.onChange (f:\dev\vue\json-editor-test\node_modules\@json-editor\json-editor\dist\jsoneditor.js:1522:1)
    at Class.setValue (f:\dev\vue\json-editor-test\node_modules\@json-editor\json-editor\dist\jsoneditor.js:5823:1)
    at Class.postBuild (f:\dev\vue\json-editor-test\node_modules\@json-editor\json-editor\dist\jsoneditor.js:1653:1)
    at Class.postBuild (f:\dev\vue\json-editor-test\node_modules\@json-editor\json-editor\dist\jsoneditor.js:6046:1)
    at Class.prototype.<computed> [as postBuild] (f:\dev\vue\json-editor-test\node_modules\@json-editor\json-editor\dist\jsoneditor.js:63:1)
    at f:\dev\vue\json-editor-test\node_modules\@json-editor\json-editor\dist\jsoneditor.js:3564:1
jsoneditor.js:1588

### Steps to reproduce the behavior

schema example:

          strings: {
            type: "array",
            items: {
              type: "object",
              properties: {
                make: {
                  type: "string",
                  enum: ["Toyota", "BMW", "Honda", "Ford", "Chevy", "VW"]
                },
                model: {
                  type: "string",
                  options: {
                    dependencies: {
                      make: "Toyota"
                    }
                  }
                }
              }
            }
          },

add 2 objects then delete one. results in exception:

**Comment by germanbisurgi** [comment]
could you recreate the error here (https://json-editor.github.io/json-editor/) and then paste the post the link?

**Comment by rozo1** [comment]
https://json-editor.github.io/json-editor/?schema=N4IgLglmA2CmIC4QAVYCcDOB7AdiANOAJ4AO8SWARgFawDGYBIasAjgK4QsAmiA2iBwBDALbxCQgObiQ3IWBkAzIQDcsaKLAD6dLNHVNpObuib668iLiZkwGEAF1CJNFjJpIsewlDCxiUDBSchAMMA0cSSYTDDoNEkhrJAAxLjCAAiFjdIAZIQy/GREIHBzYSLAAC0QAFkITZXZoRiQAKXRYESJ0gBF1PABfCWkA4jJEEBKFaTRo2EbmxAAmAFZCYpwIEXYRRABGAA51oQAPLZ3EAE5LoZBlNQ0FHT0DHzGQsIiowkV1EXkJrp9LNCJAYCF7upNOkgQZ6vMhE0WiAAMSKZQrAAMmJAtyMJlmbyC4yQnxK3xA5QuCAE/zgTEUnSE9IctzkClGxI+4XJDL+AKQ7JkbkSOG8oEU0HkJAgdAA1oTgANlYRzJYkoFghMqLQGEwwfSkDksBZRTZXO5POKQHQoEROVrSTzInMFsiAMpZdLJNBZW2xLC4whheTkTUk0LOikNRGLJAAYQAgkGbXaQxyiY7I185rF4makAAVSoQDDpUvpIzoUPcTLsMBYf6QCzQaDdRSuETpKqwdIuWAqKzsMtgADuWHSiggsGg3HsoM6JClGZAwGAtqCKvSa/TsGVTFH8jo1TeG/tSDVooAdGemLuJperDgr/flSqQLZrVyJkI0L77YQmgiF+WY6vQjCglAhooLAEEfha6BWg6JLhtyOaEFSuw0jaAL1FgFKUFwvCECwCQQPShBYD2sysoQhTIWhvKUWRuDWiYZDGOUtpeAxEzcPhuJvmyCJIvwqF8QJdGiCEADqzIKLMAyssqQA=&value=N4IgdghgtgpiBcIBSMBOMoE8AEARA9qmCADQgQDmc8ATAKxkBmEAboQJYAuMA+gMb4ANoQQgAxI2Z0ADNNIgqYACZpRUCILhklEbqPnC+u9vmLxgAXzIAHGJwDOCANqhOmW6KX4K8yLFEA6hrcqCBWru7UIEacvtBRYSQRHogxcf6IYQC6FkA===&lib_switcher=&prompt_before_delete&upload=function(a,b,c){console.log(%22Upload%20handler%20required%20for%20upload%20editor%22)}&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction

**Comment by schmunk42** [comment]
@rozo1 Thank you, nice find.

Would be great to reproduce this with a (failing) test first. (CC: @germanbisurgi)

**Comment by pmk65** [comment]
More simplified test example: https://is.gd/Bx1Ft6
