### ISSUE TITLE
docker-test npm script does not run tests but passes with message - shows 'OK | 0 passed'

### ISSUE THREAD

**Issue by sirockin** [json-editor/json-editor#484]
### General information
I'm seeing this while working on the development branch from a Windows 10 machine.

The commit I'm using as an example has three failing tests but these are not picked up when runing the script.

Since the tests work as designed when each step in the script is run individually, I imagine it's due to a race condition between the containers, which could possibly be fixed by using `depends_on` docker-compose entry.

- json-editor version:
1.4.0-beta.0 (dev 2.x branch)
commit: 72fc61eca7cea08d9361f9fed34a5cff390fe152

I get identical results having replaced all the grunt scripts with webpack onces in my new webpack fork which I will submit later today as a PR, and is descended from the above commit.

### Expected behavior
When I run `npm run docker-test` I should see "OK | n passed " where n is a non-zero number.

### Actual behavior
When I run `npm run docker-test` I should see "OK | 0 passed "

```bash
PS C:\flow\forks\json-editor-master> npm run docker-test

> @json-editor/json-editor@1.4.0-beta.0 docker-test C:\flow\forks\json-editor-master
> cd tests && docker-compose run --rm node npm run build && docker-compose up -d && docker-compose ps && docker-compose run --rm codeceptjs codeceptjs run-multiple basic --grep '(?=.*)^(?!.*@optional)'

Creating network "tests_default" with the default driver

> @json-editor/json-editor@1.4.0-beta.0 build /repo
> npm install && grunt

npm WARN lifecycle @json-editor/json-editor@1.4.0-beta.0~prepare: cannot run in wd @json-editor/json-editor@1.4.0-beta.0 grunt (wd=/repo)
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} 
(current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/watchify/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} 
(current: {"os":"linux","arch":"x64"})

audited 6470 packages in 15.579s
found 0 vulnerabilities

Running "jshint:beforeconcat" (jshint) task
>> 72 files lint free.

Running "concat:dist" (concat) task

Running "jshint:afterconcat" (jshint) task
>> 1 file lint free.

Running "uglify:dist" (uglify) task
File dist/jsoneditor.min.js.map created (source map).
File dist/jsoneditor.min.js created: 412.88 kB → 237.83 kB
>> 1 sourcemap created.
>> 1 file created.

Running "cssmin:combine" (cssmin) task
>> 1 file created. 1.1 kB → 763 B

Done.
Creating tests_node_1       ... done
Creating tests_codeceptjs_1 ... done
Creating tests_chrome_1     ... done
Creating tests_firefox_1    ... done
The system cannot find the path specified.
       Name                     Command               State                         Ports
--------------------------------------------------------------------------------------------------------------
tests_chrome_1       /opt/bin/entry_point.sh          Up       0.0.0.0:32778->4444/tcp, 0.0.0.0:9060->5900/tcp
tests_codeceptjs_1   /codecept/docker/entrypoin ...   Exit 1
tests_firefox_1      /opt/bin/entry_point.sh          Up       0.0.0.0:32779->4444/tcp, 0.0.0.0:9059->5900/tcp
tests_node_1         docker-entrypoint.sh npm r ...   Up       0.0.0.0:9001->9001/tcp, 0.0.0.0:9010->9010/tcp
[1.basic:firefox] CodeceptJS v2.2.0
[1.basic:firefox] Using test root "/repo/tests/codeceptjs"


[1.basic:firefox]   OK  | 0 passed   // 1ms
[2.basic:chrome] CodeceptJS v2.2.0
[2.basic:chrome] Using test root "/repo/tests/codeceptjs"


[2.basic:chrome]   OK  | 0 passed   // 1ms
PS C:\flow\forks\json-editor-master> 
```

### Steps to reproduce the behavior
```bash
npm run docker-test
```
If I run the individual steps in the script one by one I do see the expected result. IE:

```bash
PS C:\flow\forks\json-editor-master> cd tests
PS C:\flow\forks\json-editor-master\tests> docker-compose run --rm node npm run build

> @json-editor/json-editor@1.4.0-beta.0 build /repo
> npm install && grunt

npm WARN lifecycle @json-editor/json-editor@1.4.0-beta.0~prepare: cannot run in wd @json-editor/json-editor@1.4.0-beta.0 grunt (wd=/repo)
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} 
(current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/watchify/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} 
(current: {"os":"linux","arch":"x64"})

audited 6470 packages in 15.48s
found 0 vulnerabilities

Running "jshint:beforeconcat" (jshint) task
>> 72 files lint free.

Running "concat:dist" (concat) task

Running "jshint:afterconcat" (jshint) task
>> 1 file lint free.

Running "uglify:dist" (uglify) task
File dist/jsoneditor.min.js.map created (source map).
File dist/jsoneditor.min.js created: 412.88 kB → 237.83 kB
>> 1 sourcemap created.
>> 1 file created.

Running "cssmin:combine" (cssmin) task
>> 1 file created. 1.1 kB → 763 B

Done.
PS C:\flow\forks\json-editor-master\tests> docker-compose up -d
Starting tests_codeceptjs_1 ...
tests_node_1 is up-to-date
tests_chrome_1 is up-to-date
Starting tests_codeceptjs_1 ... done
PS C:\flow\forks\json-editor-master\tests>docker-compose ps
The system cannot find the path specified.
       Name                     Command               State                         Ports
--------------------------------------------------------------------------------------------------------------
tests_chrome_1       /opt/bin/entry_point.sh          Up       0.0.0.0:32778->4444/tcp, 0.0.0.0:9060->5900/tcp
tests_codeceptjs_1   /codecept/docker/entrypoin ...   Exit 1
tests_firefox_1      /opt/bin/entry_point.sh          Up       0.0.0.0:32779->4444/tcp, 0.0.0.0:9059->5900/tcp
tests_node_1         docker-entrypoint.sh npm r ...   Up       0.0.0.0:9001->9001/tcp, 0.0.0.0:9010->9010/tcp
PS C:\flow\forks\json-editor-master\tests> docker-compose run --rm codeceptjs codeceptjs run-multiple basic --grep '(?=.*)^(?!.*@optional)'
[1.basic:firefox] CodeceptJS v2.2.0
[1.basic:firefox] Using test root "/repo/tests/codeceptjs"

[1.basic:firefox] core --
[2.basic:chrome] CodeceptJS v2.2.0
[2.basic:chrome] Using test root "/repo/tests/codeceptjs"

[2.basic:chrome] core --
[2.basic:chrome]   ✔ should Disable and enable entire form in 1022ms
[2.basic:chrome]   ✔ should Disable and enable part of the form in 718ms
[1.basic:firefox]   ✔ should Disable and enable entire form in 1297ms
[2.basic:chrome]   ✔ should destroy in 317ms
[2.basic:chrome]   ✔ should set and get form value in 541ms
[2.basic:chrome]   ✔ should set and get individual values in 614ms
[1.basic:firefox]   ✔ should Disable and enable part of the form in 927ms
[2.basic:chrome]   ✔ should watch a specific field for changes in 396ms
[2.basic:chrome] Advanced Editor --
[2.basic:chrome]   ✔ test validation & delete in 839ms
[2.basic:chrome] array --
[2.basic:chrome]   ✔ should have correct initial value in 404ms
[1.basic:firefox]   ✔ should destroy in 684ms
[2.basic:chrome]   ✔ should array editing triggers in 1502ms
[1.basic:firefox]   ✔ should set and get form value in 1193ms
[2.basic:chrome]   ✔ should work well with string editors in 3703ms
[1.basic:firefox]   ✔ should set and get individual values in 905ms
[2.basic:chrome]   ✔ should work well with number editors in 3526ms
[1.basic:firefox]   ✔ should watch a specific field for changes in 700ms
[1.basic:firefox] Advanced Editor --
[2.basic:chrome]   ✔ should work well with integer editors in 3943ms
[1.basic:firefox]   ✔ test validation & delete in 752ms
[1.basic:firefox] array --
[2.basic:chrome]   ✔ should work well with select editors in 2825ms
[1.basic:firefox]   ✔ should have correct initial value in 610ms
[2.basic:chrome]   ✔ should work well with checkbox editors in 4120ms
[1.basic:firefox]   ✔ should array editing triggers in 2410ms
[2.basic:chrome]   ✔ should work well with rating editors in 2689ms
[2.basic:chrome]   ✔ should work well with multiselect editors in 3721ms
[1.basic:firefox]   ✔ should work well with string editors in 4513ms
[2.basic:chrome]   ✔ should work well with object editors in 3960ms
[1.basic:firefox]   ✔ should work well with number editors in 4597ms
[1.basic:firefox]   ✔ should work well with integer editors in 4354ms
[1.basic:firefox]   ✔ should work well with select editors in 4447ms
[2.basic:chrome]   ✔ should work well with nested array editors in 31861ms
[1.basic:firefox]   ✔ should work well with checkbox editors in 6274ms
[1.basic:firefox]   ✔ should work well with rating editors in 3314ms
[2.basic:chrome]   ✖ should work well with selectize multiselect editors in 5808ms
[2.basic:chrome] checkbox --
[2.basic:chrome]   ✔ should be disabled if "readonly" is specified in 303ms
[2.basic:chrome] inheritance --
[2.basic:chrome]   ✔ should display all required fields in the allOf hierarchy in 373ms
[2.basic:chrome] integer --
[2.basic:chrome]   ✔ should have correct initial value in 288ms
[2.basic:chrome]   ✔ should respect step by incrementing and decrementing the value of a number in 480ms
[2.basic:chrome]   ✔ should respect step by incrementing and decrementing the value of a range in 391ms
[2.basic:chrome]   ✔ should be readonly if specified and not disabled in 314ms
[2.basic:chrome] multiselect --
[1.basic:firefox]   ✔ should work well with multiselect editors in 5506ms
[2.basic:chrome]   ✔ should be disabled if "readonly" is specified in 332ms
[2.basic:chrome] number --
[2.basic:chrome]   ✔ should have correct initial value in 331ms
[2.basic:chrome]   ✔ should respect step by incrementing and decrementing the value of a number in 470ms
[2.basic:chrome]   ✔ should respect step by incrementing and decrementing the value of a range in 508ms
[2.basic:chrome]   ✔ should be readonly if specified and not disabled in 286ms
[2.basic:chrome] object --
[2.basic:chrome]   ✔ should respect property orders in 505ms
[2.basic:chrome]   ✖ should validate required properties in 416ms
[1.basic:firefox]   ✔ should work well with object editors in 5823ms
[2.basic:chrome]   ✔ should validate also not required properties in 416ms
[2.basic:chrome]   ✔ grid-strict rows and columns in 1900ms
[2.basic:chrome]   ✔ grid rows and columns in 962ms
[2.basic:chrome]   ✔ opt in optional properties in 1336ms
[2.basic:chrome] Programmatic changes --
[2.basic:chrome]   ✖ should have correct initial value in 5530ms
[2.basic:chrome] rating --
[2.basic:chrome]   ✔ should be disabled if "readonly" is specified in 306ms
[2.basic:chrome] select --
[2.basic:chrome]   ✔ should return correct booleans values when selected in 754ms
[2.basic:chrome]   ✔ should be disabled if "readonly" is specified in 282ms
[2.basic:chrome] string --
[2.basic:chrome]   ✔ should have correct initial value in 412ms
[2.basic:chrome]   ✔ should have coerent values in 810ms
[2.basic:chrome]   ✔ should have correct initial value in 402ms
[2.basic:chrome]   ✔ should be readonly if specified and not disabled in 280ms
[2.basic:chrome]   ✔ should have a custom attribute with custom value in 325ms
[2.basic:chrome] table --
[2.basic:chrome]   ✔ should have correct initial value in 373ms
[2.basic:chrome]   ✔ should ask for confirmation on node delete in 556ms
[2.basic:chrome]   ✔ should ask for confirmation on node delete last in 659ms
[2.basic:chrome]   ✔ should ask for confirmation on node delete all in 778ms
[2.basic:chrome] Tabs --
[2.basic:chrome]   ✔ test top-tabs in 1713ms
[2.basic:chrome] Validations --
[2.basic:chrome]   ✔ test validations in validation.html in 1874ms

[2.basic:chrome] -- FAILURES:

  1) array
       should work well with selectize multiselect editors:
     Element "[data-schemapath="root.0"] .selectize-input [data-value="1"] a.remove" was not found by text|CSS|XPath       

  Scenario Steps:

  - I.seeElement("[data-schemapath="root.0"] .selectize-input [data-value="1"] a.remove") at Test.Scenario (editors/array_test.js:757:5)
  - I.grabValueFrom(".debug") at Test.Scenario (editors/array_test.js:752:19)
  - I.click(".get-value") at Test.Scenario (editors/array_test.js:751:5)
  - I.seeElement("[data-schemapath="root.1"]") at Test.Scenario (editors/array_test.js:750:5)
  - I.seeElement("[data-schemapath="root.0"]") at Test.Scenario (editors/array_test.js:749:5)
  - I.click("Add item") at Test.Scenario (editors/array_test.js:748:5)
  - I.click("Add item") at Test.Scenario (editors/array_test.js:747:5)
  - I.amOnPage("array-selectize.html") at Test.Scenario (editors/array_test.js:746:5)



  Run with --verbose flag to see NodeJS stacktrace

  2) object
       should validate required properties:

      expected web page to include "Value must be at least 18."
      + expected - actual

      -get value
      -PersonCollapseEdit JSON
      -Object Properties
      -Age
      -Name
      -Single
      - true
      -false
      -Values
      - value A value B
      ---( 2 lines more )---
      +Value must be at least 18.


  Scenario Steps:

  - I.see("Value must be at least 18.") at Test.Scenario (editors/object_test.js:16:5)
  - I.amOnPage("object.html") at Test.Scenario (editors/object_test.js:15:5)



  Run with --verbose flag to see NodeJS stacktrace

  3) Programmatic changes
       should have correct initial value:
     element (.state) is not in DOM or there is no element(.state) with text "READY" after 5 sec

  Scenario Steps:

  - I.waitForText("READY", 5, ".state") at Test.Scenario (editors/programmatic-changes_test.js:7:5)
  - I.amOnPage("programmatic-changes.html") at Test.Scenario (editors/programmatic-changes_test.js:6:5)



  Run with --verbose flag to see NodeJS stacktrace


[2.basic:chrome]   FAIL  | 48 passed, 3 failed   // 3m
[1.basic:firefox]   ✔ should work well with nested array editors in 37645ms
[1.basic:firefox]   ✖ should work well with selectize multiselect editors in 8360ms
[1.basic:firefox] checkbox --
[1.basic:firefox]   ✔ should be disabled if "readonly" is specified in 382ms
[1.basic:firefox] inheritance --
[1.basic:firefox]   ✔ should display all required fields in the allOf hierarchy in 338ms
[1.basic:firefox] integer --
[1.basic:firefox]   ✔ should have correct initial value in 602ms
[1.basic:firefox]   ✔ should respect step by incrementing and decrementing the value of a number in 800ms
[1.basic:firefox]   ✔ should respect step by incrementing and decrementing the value of a range in 830ms
[1.basic:firefox]   ✔ should be readonly if specified and not disabled in 308ms
[1.basic:firefox] multiselect --
[1.basic:firefox]   ✔ should be disabled if "readonly" is specified in 262ms
[1.basic:firefox] number --
[1.basic:firefox]   ✔ should have correct initial value in 527ms
[1.basic:firefox]   ✔ should respect step by incrementing and decrementing the value of a number in 789ms
[1.basic:firefox]   ✔ should respect step by incrementing and decrementing the value of a range in 877ms
[1.basic:firefox]   ✔ should be readonly if specified and not disabled in 337ms
[1.basic:firefox] object --
[1.basic:firefox]   ✔ should respect property orders in 390ms
[1.basic:firefox]   ✖ should validate required properties in 494ms
[1.basic:firefox]   ✔ should validate also not required properties in 359ms
[1.basic:firefox]   ✔ grid-strict rows and columns in 1056ms
[1.basic:firefox]   ✔ grid rows and columns in 630ms
[1.basic:firefox]   ✔ opt in optional properties in 2494ms
[1.basic:firefox] Programmatic changes --
[1.basic:firefox]   ✖ should have correct initial value in 5378ms
[1.basic:firefox] rating --
[1.basic:firefox]   ✔ should be disabled if "readonly" is specified in 414ms
[1.basic:firefox] select --
[1.basic:firefox]   ✔ should return correct booleans values when selected in 1412ms
[1.basic:firefox]   ✔ should be disabled if "readonly" is specified in 289ms
[1.basic:firefox] string --
[1.basic:firefox]   ✔ should have correct initial value in 558ms
[1.basic:firefox]   ✔ should have coerent values in 1284ms
[1.basic:firefox]   ✔ should have correct initial value in 516ms
[1.basic:firefox]   ✔ should be readonly if specified and not disabled in 269ms
[1.basic:firefox]   ✔ should have a custom attribute with custom value in 322ms
[1.basic:firefox] table --
[1.basic:firefox]   ✔ should have correct initial value in 484ms
[1.basic:firefox]   ✔ should ask for confirmation on node delete in 708ms
[1.basic:firefox]   ✔ should ask for confirmation on node delete last in 903ms
[1.basic:firefox]   ✔ should ask for confirmation on node delete all in 948ms
[1.basic:firefox] Tabs --
[1.basic:firefox]   ✔ test top-tabs in 2626ms
[1.basic:firefox] Validations --
[1.basic:firefox]   ✔ test validations in validation.html in 2013ms

[1.basic:firefox] -- FAILURES:

  1) array
       should work well with selectize multiselect editors:
     Element "[data-schemapath="root.0"] .selectize-input [data-value="1"] a.remove" was not found by text|CSS|XPath       

  Scenario Steps:

  - I.seeElement("[data-schemapath="root.0"] .selectize-input [data-value="1"] a.remove") at Test.Scenario (editors/array_test.js:757:5)
  - I.grabValueFrom(".debug") at Test.Scenario (editors/array_test.js:752:19)
  - I.click(".get-value") at Test.Scenario (editors/array_test.js:751:5)
  - I.seeElement("[data-schemapath="root.1"]") at Test.Scenario (editors/array_test.js:750:5)
  - I.seeElement("[data-schemapath="root.0"]") at Test.Scenario (editors/array_test.js:749:5)
  - I.click("Add item") at Test.Scenario (editors/array_test.js:748:5)
  - I.click("Add item") at Test.Scenario (editors/array_test.js:747:5)
  - I.amOnPage("array-selectize.html") at Test.Scenario (editors/array_test.js:746:5)



  Run with --verbose flag to see NodeJS stacktrace

  2) object
       should validate required properties:

      expected web page to include "Value must be at least 18."
      + expected - actual

      -get value
      -PersonCollapseEdit JSON
      -Object Properties
      -Age
      -Name
      -Single
      -true
      -false
      -Values
      - value A value B
      ---( 2 lines more )---
      +Value must be at least 18.


  Scenario Steps:

  - I.see("Value must be at least 18.") at Test.Scenario (editors/object_test.js:16:5)
  - I.amOnPage("object.html") at Test.Scenario (editors/object_test.js:15:5)



  Run with --verbose flag to see NodeJS stacktrace

  3) Programmatic changes
       should have correct initial value:
     element (.state) is not in DOM or there is no element(.state) with text "READY" after 5 sec

  Scenario Steps:

  - I.waitForText("READY", 5, ".state") at Test.Scenario (editors/programmatic-changes_test.js:7:5)
  - I.amOnPage("programmatic-changes.html") at Test.Scenario (editors/programmatic-changes_test.js:6:5)



  Run with --verbose flag to see NodeJS stacktrace


[1.basic:firefox]   FAIL  | 48 passed, 3 failed   // 5m
```

**Comment by schmunk42** [comment]
Could you try to remove the `--grep ...` option from https://github.com/json-editor/json-editor/blob/1bebfc1240cd30935e54607c8fd045b95bd80775/package.json#L33 locally, to see if some of the chars are messing up the tests on Windows?

**Comment by sirockin** [comment]
Yes that fixed it, thanks! (Although obviously @optional tests weren't filtered out).

**Comment by pmk65** [comment]
> 
> 
> Yes that fixed it, thanks! (Although obviously @optional tests weren't filtered out).

[RegexBuddy](http://www.regexbuddy.com/) converted the regex to this (PowerShell format). Maybe that will work?
`(?=[^\n\r\u2028\u2029]*)^(?![^\n\r\u2028\u2029]*@optional)'  `

**Comment by sirockin** [comment]
Thanks Peter - no unfortunately it didn't .  Out of interest do you know why we're using this `optional` marker rather than [xScenario](https://codecept.io/basics)? It feels a bit hacky and unnecessary given the alternative.

**Comment by pmk65** [comment]
That's @schmunk42 you got to ask, not me. 😄

**Comment by schmunk42** [comment]
@sirockin Acutally @germanbisurgi wrote the tests.

We'd like to run tests, but not make them the whole build process fail.
Does `xScenario` help in this case? Would be great.

**Comment by sirockin** [comment]
According to the docs, `xScenario` simply tells codeceptjs to skip the scenario so it won't actually run the test. But presumably you don't need it to run until it's been fixed?

You'll see in unit the jasmine unit tests, there is a similar construct - `xit` - which does the same thing. Jasmine then reports the test as 'pending'.

**Comment by schmunk42** [comment]
How can we run the tests locally? Simply by removing the `x` or is there a `--param` for it?

**Comment by sirockin** [comment]
If it's the same as jasmine, you'd just have to remove the x. 

I guess the alternative - if you want tests to run in some situations and not in others - would be to check an environment variable at the start of the scenario and return immediately if it is set to a given value.

**Comment by schmunk42** [comment]
We should find a way to use the `@optional` solution, since it's pretty easy to run different sets of tests in a Travis matrix.

Actually this should be pretty easy with `--invert`, but there's an open issue: https://github.com/Codeception/CodeceptJS/issues/1093

**Comment by schmunk42** [comment]
Nevermind :see_no_evil: 

Use

```
codeceptjs run --invert --grep  '@optional'
codeceptjs run-multiple basic:firefox --invert --grep  '@optional'
```

to exclude `@optional` tests.

**Comment by sirockin** [comment]
I just created and ran the following npm script:
```json
    "docker-test-invert": "cd tests && docker-compose run --rm node npm run build && docker-compose up -d && docker-compose ps && docker-compose run --rm codeceptjs codeceptjs run-multiple basic --invert --grep  '@optional'",
```
The result was all tests (including the failing @optional ones) ran for both browsers and ended each time with:
```bash
  FAIL  | 52 passed, 3 failed   
```

**Comment by schmunk42** [comment]
```
docker-compose run --rm codeceptjs codeceptjs run-multiple basic --invert --grep  '@optional'
```

Result:

```
[2.basic:chrome]   OK  | 51 passed   // 1m
```

... on my Linux machine

Could you try to play around with the quotes? Leave them away, replace with `"`, escape, ...

**Comment by sirockin** [comment]
Yes the command on its own always worked for me - it was when run from the npm script that it was failing. I've edited the last script now to remove the single quotes altogether, and it works:
```json
    "docker-test-invert": "cd tests && docker-compose run --rm node npm run build && docker-compose up -d && docker-compose ps && docker-compose run --rm codeceptjs codeceptjs run-multiple basic --invert --grep  @optional",
```

If this works on a non-Windows machine, may I suggest updating the `docker-test` script accordingly?

**Comment by schmunk42** [comment]
> If this works on a non-Windows machine, may I suggest updating the docker-test script accordingly?

Yes, please. (works on Linux, too) - Let's see how that works out on Travis.
