### ISSUE TITLE
Question: Is it possible to use just the validator from json-editor?

### ISSUE THREAD

**Issue by bmehta** [json-editor/json-editor#883]
Question: Is there a way to just use the validator from json-editor. The use case is that we are using json-editor in the front-end and when the json is sent to the server-side, we want to validate it one more time, using the same validation that json-editor might be using. I tried the example below, without much luck. Any help will be appreciated. Thank you.

Example:
```
const config = {
		/* eslint-disable camelcase */
		schema,
		startval: data,
		/* eslint-enable */
	}

const editor = new JSONEditor(null, config);
const errors = editor.validate();
```

Error:
```
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/bmehta/Projects/authoring-navigation/node_modules/@json-editor/json-editor/dist/jsoneditor.js:14:224)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Object.require.extensions.<computed> [as .js] (/Users/bmehta/Projects/authoring-navigation/node_modules/ts-node/src/index.ts:1032:44)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at eval (webpack-internal:///@json-editor/json-editor:1:18)
    at Object.@json-editor/json-editor (/Users/bmehta/Projects/authoring-navigation/.next/server/pages/api/save.js:115:1)
```

**Comment by germanbisurgi** [comment]
if you use php for your backend you can have a look at this repo. https://github.com/justinrainbow/json-schema

**Comment by schmunk42** [comment]
Have a look at these tools https://json-schema.org/implementations.html also.

For us it's currently out of scope to support this separately.
