### ISSUE TITLE
A build/test does not work with a fresh cloned repository....

### ISSUE THREAD

**Issue by Lord-Grey** [json-editor/json-editor#888]
### General information

Doing a build/test on top of a fresh cloned repository does not work.

I am running Ubuntu 20.04

Thanks for your support...

### Actual behavior

```
npm run debug

> @json-editor/json-editor@2.5.1 debug /home/thomas/json-editor-lordgrey
> webpack-dev-server --config config/webpack.dev.js --progress

✖ ｢wds｣: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.devtool should match pattern "^(inline-|hidden-|eval-)?(nosources-)?(cheap-(module-)?)?source-map$".
   BREAKING CHANGE since webpack 5: The devtool option is more strict.
   Please strictly follow the order of the keywords in the pattern.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @json-editor/json-editor@2.5.1 debug: `webpack-dev-server --config config/webpack.dev.js --progress`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @json-editor/json-editor@2.5.1 debug script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/thomas/.npm/_logs/2020-12-31T07_25_57_067Z-debug.log
```

```
npm run eslint

> @json-editor/json-editor@2.5.1 eslint /home/thomas/json-editor-lordgrey
> eslint -c ./.eslintrc src/**/*.js

Error: .eslintrc » eslint-config-standard:
	Environment key "es2021" is unknown

    at Object.keys.forEach.id (/home/thomas/json-editor-lordgrey/node_modules/eslint/lib/shared/config-validator.js:169:19)
    at Array.forEach (<anonymous>)
    at validateEnvironment (/home/thomas/json-editor-lordgrey/node_modules/eslint/lib/shared/config-validator.js:163:30)
    at validateConfigArray (/home/thomas/json-editor-lordgrey/node_modules/eslint/lib/shared/config-validator.js:334:9)
    at CascadingConfigArrayFactory._finalizeConfigArray (/home/thomas/json-editor-lordgrey/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:417:13)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/home/thomas/json-editor-lordgrey/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:271:21)
    at FileEnumerator._iterateFilesWithFile (/home/thomas/json-editor-lordgrey/node_modules/eslint/lib/cli-engine/file-enumerator.js:320:43)
    at FileEnumerator._iterateFiles (/home/thomas/json-editor-lordgrey/node_modules/eslint/lib/cli-engine/file-enumerator.js:301:25)
    at FileEnumerator.iterateFiles (/home/thomas/json-editor-lordgrey/node_modules/eslint/lib/cli-engine/file-enumerator.js:251:59)
    at iterateFiles.next (<anonymous>)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @json-editor/json-editor@2.5.1 eslint: `eslint -c ./.eslintrc src/**/*.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @json-editor/json-editor@2.5.1 eslint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/thomas/.npm/_logs/2020-12-31T07_29_29_074Z-debug.log
```

**Comment by schmunk42** [comment]
Are you running this on your machine or in the container?
If it is your machine, which version are you using?

**Comment by Lord-Grey** [comment]
I was running in my VM which is Ubuntu 20.04 based.
If you want me to look up versions of some specific components, e.g. eslint, npm, I can do so after work...

I am also happy to run the process via container build, but there I would need some guidance by yourself, as the current documentation does not cover the steps, yet.

**Comment by schmunk42** [comment]
`Environment key "es2021" is unknown`

Is this an ENV variable/setting on your host?

**Comment by Lord-Grey** [comment]
Not that I am aware of.
Maybe I have installed eslint not correctly?
or the .eslintrc was not populated correctly by jsoneditor providing the right tags for a newer eslint version?

**Comment by Lord-Grey** [comment]
Is there any tutorial how to run the testing via docker?
I am happy to do testing on the PR via an alternative way to get it merged ;)

**Comment by schmunk42** [comment]
> Is there any tutorial how to run the testing via docker?
> I am happy to do testing on the PR via an alternative way to get it merged ;)

Does this work for you?
https://github.com/json-editor/json-editor/tree/master/tests

Which OS do you have?

**Comment by Lord-Grey** [comment]
Let me give it a try.

I am running Ubuntu 20.04.

**Comment by Lord-Grey** [comment]
@schmunk42 Thank you! The docker way worked. I got the json-editor built.
